export type Member = {
  Id: number,
  GivenName: string,
  PreferredName: string,
  Address: string,
  PostCode: string,
  MobileNumber: string,
  EmailAddress: string,
  DateOfBirth: Date,
  School: string,
  MedicalInformation: string,
  EmergencyContact1: string,
  EmergencyContact2: string,
  MembershipType: string,
  GuardianName: string,
  GuardianEmailAddress: string,
  Status: number,  
}